### ISSUE TITLE
Build failure with ffmpeg 9.0

### ISSUE THREAD

**Issue by K1ngfish3r** [ammen99/wf-recorder#350]
```bash
│B│ FAILED: [code=1] wf-recorder.p/src_frame-writer.cpp.o
│B│ clang++ -Iwf-recorder.p -I. -I.. -I/usr/include/libdrm -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 '-DWFRECORDER_VERSION="0.6.0"' -Wno-deprecated-declarations -O2 -Werror=odr -Werror=strict-aliasing -Wp,-D_GLIBCXX_ASSERTIONS -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -fcf-protection -fexceptions -ffat-lto-objects -flto=thin -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector --param ssp-buffer-size=32 -g -fasynchronous-unwind-tables -march=x86-64-v2 -mtune=ivybridge -mprefer-vector-width=128 -mtls-dialect=gnu2 -pipe -Wformat -Wformat-security -Wno-error -fPIC -fno-strict-aliasing -fno-strict-overflow -D_REENTRANT -pthread -MD -MQ wf-recorder.p/src_frame-writer.cpp.o -MF wf-recorder.p/src_frame-writer.cpp.o.d -o wf-recorder.p/src_frame-writer.cpp.o -c ../src/frame-writer.cpp
│B│ ../src/frame-writer.cpp:195:17: error: no member named 'pix_fmts' in 'AVCodec'
│B│   195 |     if (!codec->pix_fmts)
│B│       |          ~~~~~  ^
│B│ ../src/frame-writer.cpp:200:41: error: no member named 'pix_fmts' in 'AVCodec'
│B│   200 |     if (is_fmt_supported(in_fmt, codec->pix_fmts))
│B│       |                                  ~~~~~  ^
│B│ ../src/frame-writer.cpp:206:28: error: no member named 'pix_fmts' in 'AVCodec'
│B│   206 |     for (int i = 0; codec->pix_fmts[i] != AV_PIX_FMT_NONE; i++) {
│B│       |                     ~~~~~  ^
│B│ ../src/frame-writer.cpp:209:20: error: no member named 'pix_fmts' in 'AVCodec'
│B│   209 |             codec->pix_fmts[i], in_fmt, false, &loss);
│B│       |             ~~~~~  ^
│B│ ../src/frame-writer.cpp:521:17: error: no member named 'ch_layouts' in 'AVCodec'
│B│   521 |     if (!codec->ch_layouts)
│B│       |          ~~~~~  ^
│B│ ../src/frame-writer.cpp:524:46: error: no member named 'ch_layouts' in 'AVCodec'
│B│   524 |         if (!av_channel_layout_check(&codec->ch_layouts[i]))
│B│       |                                       ~~~~~  ^
│B│ ../src/frame-writer.cpp:526:20: error: no member named 'ch_layouts' in 'AVCodec'
│B│   526 |         if (codec->ch_layouts[i].u.mask == AV_CH_LAYOUT_STEREO)
│B│       |             ~~~~~  ^
│B│ ../src/frame-writer.cpp:527:27: error: no member named 'ch_layouts' in 'AVCodec'
│B│   527 |             return codec->ch_layouts[i].u.mask;
│B│       |                    ~~~~~  ^
│B│ ../src/frame-writer.cpp:530:19: error: no member named 'ch_layouts' in 'AVCodec'
│B│   530 |     return codec->ch_layouts[0].u.mask;
│B│       |            ~~~~~  ^
│B│ ../src/frame-writer.cpp:552:17: error: no member named 'sample_fmts' in 'AVCodec'
│B│   552 |     if (!codec->sample_fmts)
│B│       |          ~~~~~  ^
│B│ ../src/frame-writer.cpp:555:20: error: no member named 'sample_fmts' in 'AVCodec'
│B│   555 |         if (codec->sample_fmts[i] == -1)
│B│       |             ~~~~~  ^
│B│ ../src/frame-writer.cpp:557:44: error: no member named 'sample_fmts' in 'AVCodec'
│B│   557 |         if (av_get_bytes_per_sample(codec->sample_fmts[i]) >= 2)
│B│       |                                     ~~~~~  ^
│B│ ../src/frame-writer.cpp:558:27: error: no member named 'sample_fmts' in 'AVCodec'
│B│   558 |             return codec->sample_fmts[i];
│B│       |                    ~~~~~  ^
│B│ ../src/frame-writer.cpp:561:19: error: no member named 'sample_fmts' in 'AVCodec'
│B│   561 |     return codec->sample_fmts[0];
│B│       |            ~~~~~  ^
│B│ ../src/frame-writer.cpp:565:59: error: no member named 'sample_fmts' in 'AVCodec'
│B│   565 |     for (const enum AVSampleFormat *sample_ptr = codec -> sample_fmts; *sample_ptr != -1; sample_ptr++)
│B│       |                                                  ~~~~~    ^
│B│ ../src/frame-writer.cpp:582:24: error: no member named 'sample_fmts' in 'AVCodec'
│B│   582 |     } else if (!codec->sample_fmts || check_fmt_available(codec, converted_fmt))
│B│       |                 ~~~~~  ^
│B│ 16 errors generated.
```

OS: AerynOS
version: volatile (bleeding edge)

I tried bringing over `https://github.com/opencv/opencv/pull/29533` but am too noob to correctly implement it

**Comment by lfos** [comment]
We're facing the same issue trying to package `wf-recorder` for Arch Linux with the most recent ffmpeg release.

**Comment by diederikdehaas** [comment]
Also on Debian: https://bugs.debian.org/1144022

**Comment by lfos** [comment]
@diederikdehaas - FYI, we were able to build against ffmpeg 9 with this patch: https://gitlab.archlinux.org/archlinux/packaging/packages/wf-recorder/-/blob/d85efa2704043e629f2c47002fea6f98b02ee497/ffmpeg-9.patch

**Comment by mmirus** [comment]
Ditto in nixpkgs. https://github.com/NixOS/nixpkgs/pull/552231

**Comment by rathann** [comment]
I'm working on updating FFmpeg 9 in Fedora and I can confirm that the ArchLinux patch mentioned above fixes build with FFmpeg 9.0.1. Kudos to its author and @lfos .

**Comment by ravi-arnan** [comment]
I have a patch for this and can open a PR, unless @lfos or whoever wrote the Arch patch would
rather send theirs upstream. Say the word and I will stand down.

I wrote it against the ffmpeg headers rather than from the Arch patch, so it is worth comparing the
two. What I measured on NixOS, which has 7.1.5, 8.1.2 and 9.0 side by side:

- libavcodec **62** (ffmpeg 8) marks `pix_fmts`, `sample_fmts`, `supported_samplerates`,
  `supported_framerates` and `ch_layouts` `attribute_deprecated` and ships
  `avcodec_get_supported_config()`.
- libavcodec **63** (ffmpeg 9) removes the fields. The function is unchanged.
- The function exists as far back as libavcodec 61.19 (ffmpeg 7.1), so keying the switch on
  `LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(62, 0, 100)` is conservative and also silences the
  deprecation warnings for everyone on ffmpeg 8.

The reason the call sites barely change is in the header: the returned list is "terminated by a
config-specific terminator, or NULL if all possible values are supported", and the terminators are
the same ones the arrays used (`AV_PIX_FMT_NONE`, `AV_SAMPLE_FMT_NONE`, a zeroed layout). NULL also
lines up with what the existing code already does for a NULL array. So the loops and the NULL
checks stay as they are and only the lookup moves behind a helper.

I checked that rather than trusting the docs. On ffmpeg 8, where both APIs exist, I walked every
encoder `av_codec_iterate` returns and compared the deprecated array against
`avcodec_get_supported_config()` element by element for pixel formats, sample formats and channel
layouts:

```
encoders checked: 214, mismatches: 0
```

Build results for the patch, same source tree, three ffmpeg versions: 9.0 fails without it with the
`no member named 'pix_fmts'` errors from this issue and builds with it, 8.1.2 and 7.1.5 build either
way. Recorded on a headless sway with the ffmpeg 9 build to check it is not just a compile fix: the
output is a valid 1280x720 h264 `yuv420p` matroska that decodes fully, which exercises the ported
pixel format selection.
